# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('member1', models.CharField(max_length=200)),
                ('member2', models.CharField(max_length=200)),
                ('crypts_wave', models.IntegerField(default=0)),
                ('crypts_remaining', models.IntegerField(default=0)),
            ],
        ),
    ]
