# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20171023_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='name',
        ),
    ]
