# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171004_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unpacked',
            field=models.BooleanField(default=False),
        ),
    ]
