# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_unpacked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unpacked', models.BooleanField(default=False)),
                ('setup', models.BooleanField(default=False)),
                ('connected', models.BooleanField(default=False)),
            ],
        ),
    ]
