# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unpacked',
        ),
    ]
