# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_homeinfo_post_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='connected',
            new_name='checkDrinks',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='setup',
            new_name='doRevel',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='unpacked',
            new_name='getGames',
        ),
        migrations.AddField(
            model_name='todo',
            name='makePicks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='sayHi',
            field=models.BooleanField(default=False),
        ),
    ]
