# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_caps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeinfo',
            name='details',
            field=models.TextField(blank=True, max_length=5000),
        ),
    ]
